from PyQt5.QtGui import QFont


pixel1 = QFont("DS Pixel Cyr", 16)
pixel2 = QFont("Pixel", 16)
pixel3 = QFont("Comic Sans MS pixel rus eng", 16)
pixel4 = QFont("Pixel Digivolve Cyrillic", 16)
pixel5 = QFont("Pixel LCD7", 16)
pixel6 = QFont("Pixel Times Bold", 16)
pixel7 = QFont("DS Pixel Cyr", 16)
pixel8 = QFont("Pixel Times Bold", 16)
inverkrug = QFont("mr_InverkrugOutline", 16)
coder = QFont("Codename Coder Free 4F", 16)
konstanting = QFont("Konstanting", 16)
capture = QFont("Capture Smallz", 16)
apex = QFont("mr_ApexMk3", 16)
facon = QFont("Facon", 16)
gasrux = QFont("Gasrux", 16)
caesar = QFont("CaesarDressing Cyrillic", 16)
porta = QFont("mr_PortaLightG", 16)
